services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pcos-backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pcos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always